# Generated by Django 2.1 on 2018-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datepicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='wordinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('word_name', models.CharField(max_length=200)),
                ('word_Transliteration', models.CharField(max_length=100)),
                ('word_meaning', models.CharField(max_length=500)),
                ('word_synonyms', models.CharField(max_length=500)),
                ('word_english', models.CharField(max_length=100)),
                ('word_usage', models.CharField(max_length=1000)),
                ('quote', models.CharField(max_length=2000)),
                ('poem', models.CharField(max_length=2000)),
            ],
        ),
    ]
