# Generated by Django 2.1 on 2018-09-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datepicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='wordinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('word_name', models.CharField(max_length=20)),
                ('word_meaning', models.CharField(max_length=50)),
                ('word_opposite', models.CharField(max_length=50)),
                ('word_synonyms', models.CharField(max_length=50)),
                ('word_usage', models.CharField(max_length=50)),
            ],
        ),
    ]
